runtime: python27
api_version: 1
threadsafe: yes
skip_files:
- ^node_modules$
- ^\.git$

handlers:
- url: /(robots\.txt)
  static_files: \1
  upload: (robots\.txt)
- url: /dist
  expiration: 1h
  static_dir: dist
- url: /load
  script: main.app
  login: admin
- url: .*
  script: main.app
  secure: always
