runtime: python27
api_version: 1
threadsafe: yes
skip_files:
- ^node_modules/.*
- ^\.git/.*

handlers:
- url: /manifest.json
  static_files: manifest.json
  upload: manifest.json
- url: /dist/images
  expiration: 1d
  static_dir: dist/images
- url: /dist
  expiration: 365d
  application_readable: true
  static_dir: dist
- url: /load
  script: main.app
  login: admin
- url: .*
  script: main.app
  secure: always
