name: Deploy to Google Cloud

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - uses: google-github-actions/setup-gcloud@v0
      - run: npm ci
      - run: npm run build --if-present
      - id: Deploy
        uses: google-github-actions/deploy-appengine@v0
        with:
          deliverables: app.yaml cron.yaml
          project_id: ${{ secrets.GCP_PROJECT }}